export const fa = {
   app: {
      fallbackWorkspace: 'تسکارا',
      loading: 'در حال بارگذاری...',
      back: 'بازگشت',
      clear: 'پاک‌کردن',
      unknown: 'نامشخص',
      unset: 'تعیین نشده',
      noDate: 'بدون تاریخ',
      empty: 'موردی برای نمایش وجود ندارد.',
      save: 'ثبت',
      cancel: 'لغو',
      close: 'بستن',
      more: 'بیشتر',
      search: 'جستجو',
      create: 'ایجاد',
      confirm: 'تایید',
      smsConfirmDescription: 'از ارسال پیامک مطمئن هستید؟',
   },
   nav: {
      inbox: 'صندوق ورودی',
      communications: 'اعلان‌ها',
      announcements: 'اعلان‌ها',
      meetings: 'جلسه‌ها',
      wiki: 'دانش‌نامه',
      allTasks: 'همه کارها',
      myIssues: 'کارهای من',
      workspace: 'فضای کاری',
      projects: 'پروژه‌ها',
      milestones: 'مایلستون‌ها',
      views: 'نماها',
      more: 'بیشتر',
      teams: 'تیم‌ها',
      issues: 'کارها',
      managerLoop: 'کار مدیر',
      cockpit: 'میز مدیر',
      teamHealth: 'سلامت تیم‌ها',
      reviews: 'بازبینی‌های من',
      peopleWorkload: 'بار افراد',
      capacitySettings: 'ظرفیت و توافق‌ها',
      heartbeat: 'نبض تیم‌ها',
      todayPlan: 'برنامه امروز',
      members: 'اعضا',
      settings: 'تنظیمات',
      reports: 'گزارش AI',
      cycles: 'چرخه‌ها',
      try: 'امکانات',
      recentActivity: 'آخرین تغییرات',
      createIssue: 'ایجاد کار',
      commandMenu: 'منوی فرمان',
      keyboardShortcuts: 'میانبرهای صفحه‌کلید',
      decisionQueues: 'تصمیم‌های امروز',
   },
   pages: {
      inboxDescription: 'اعلان‌های مرتبط با کارهای تسکارا و آخرین رویدادهای فضای کاری.',
      communicationsDescription: 'اعلان‌ها، جلسه‌ها، مخاطبان، وضعیت خواندن، پیامک و کارهای خروجی در یک نمای یکپارچه.',
      announcementsDescription: 'اعلان‌های سازمانی، مخاطبان، وضعیت خواندن و ارسال دستی پیامک.',
      meetingsDescription: 'جلسه‌ها، صورت‌جلسه‌ها، شرکت‌کننده‌ها و تبدیل خروجی جلسه به کارهای قابل پیگیری.',
      wikiDescription: 'دانش ماندگار فضای کاری، صفحه‌های تأییدشده، راهنماها و منابع پروژه‌ها.',
      allTasksDescription: 'نمای همه کارها در تمام تیم‌ها و پروژه‌های فضای کاری.',
      membersDescription: 'نمای کاربران، نقش‌ها، اتصال مترموست و حجم کار جاری.',
      teamHealthDescription: 'نمای تشخیصی گلوگاه‌ها، ظرفیت، بازبینی، ریسک پروژه و جریان کار تیم.',
      projectsDescription: 'فهرست پروژه‌ها با ساختار و رفتار نزدیک به لینیر.',
      milestonesDescription: 'هدف‌های پروژه‌ای برای تحویل ویژگی‌ها و پیش‌بردن فازهای اجرایی.',
      heartbeatDescription: 'نمای زنده از وضعیت کارها، پیشرفت، ریسک‌ها و به‌روزرسانی‌های همه تیم‌ها.',
      todayPlanDescription: 'برنامه امروز و کارهای عقب‌افتاده هر نفر بر اساس وزن کارها و ظرفیت روزانه.',
      settingsDescription: 'مدیریت فضای کاری، ساخت کاربران جدید، و کنترل نقش‌ها از همین صفحه.',
      reportsDescription: 'تحلیل داده تسک‌ها با هوش مصنوعی، بر اساس بازه زمانی یا ماه انتخابی.',
      issuesDescription: 'نمای اصلی کارها با گروه‌بندی وضعیت، جزئیات کناری، و میانبرهای سبک لینیر.',
      teamsDescription: 'ساخت و مرور تیم‌های داخلی برای سازمان‌دهی پروژه‌ها و اعضا.',
      cockpitDescription: 'یک صف اولویت‌بندی‌شده برای هر چیزی که اکنون به اقدام مدیر نیاز دارد.',
      decisionQueuesDescription: 'کارهای مشخصی که امروز باید درباره آن‌ها تصمیم بگیرید: بازبینی، تریاژ، واگذاری و مانع.',
      reviewsDescription: 'صف بازبینی‌های سپرده‌شده به شما، با تصمیم مستقیم و لینک به کار اصلی.',
      peopleWorkloadDescription: 'نمای عملیاتی ظرفیت، فشار کاری، چک‌این، ۱:۱ و کارهای فعلی هر نفر.',
      capacitySettingsDescription: 'تنظیم ظرفیت افراد، WIP، SLA بازبینی، SLA انسداد و آستانه رکود برای سلامت کار.',
   },
   status: {
      BACKLOG: 'بک‌لاگ',
      TODO: 'برای انجام',
      IN_PROGRESS: 'در حال انجام',
      IN_REVIEW: 'در بازبینی',
      BLOCKED: 'مسدود',
      DONE: 'انجام‌شده',
      CANCELED: 'لغوشده',
   },
   priority: {
      NO_PRIORITY: 'بدون اولویت',
      LOW: 'کم',
      MEDIUM: 'متوسط',
      HIGH: 'زیاد',
      URGENT: 'فوری',
   },
   projectStatus: {
      ACTIVE: 'فعال',
      PAUSED: 'متوقف',
      COMPLETED: 'تکمیل‌شده',
      ARCHIVED: 'آرشیوشده',
   },
   role: {
      OWNER: 'مالک',
      ADMIN: 'مدیر',
      MEMBER: 'عضو',
      GUEST: 'مهمان',
      AGENT: 'عامل',
   },
   settings: {
      workspace: 'فضای کاری',
      workspaceOverview: 'نمای کلی فضای کاری و کاربر فعلی.',
      currentUser: 'کاربر فعلی',
      unreadNotifications: 'اعلان خوانده‌نشده',
      createUser: 'ایجاد کاربر',
      createUserDescription: 'کاربر را بسازید و مستقیم به فضای کاری اضافه کنید.',
      name: 'نام',
      email: 'ایمیل',
      phone: 'شماره موبایل',
      mattermostUsername: 'نام کاربری مترموست',
      role: 'نقش',
      creating: 'در حال ثبت...',
      accessManagement: 'مدیریت دسترسی',
      accessDescription: 'نقش کاربران را تغییر دهید. API از حذف آخرین مالک جلوگیری می‌کند.',
      noUsers: 'کاربری برای مدیریت وجود ندارد.',
      loadFailed: 'بارگذاری تنظیمات ناموفق بود.',
      createFailed: 'ایجاد کاربر ناموفق بود.',
      roleUpdateFailed: 'به‌روزرسانی نقش ناموفق بود.',
   },
   knowledge: {
      title: 'دانش‌نامه',
      allSpaces: 'فضاها',
      pages: 'صفحه‌ها',
      newSpace: 'فضای جدید',
      newPage: 'صفحه جدید',
      newChildPage: 'زیرصفحه',
      createSpace: 'ایجاد فضا',
      createPage: 'ایجاد صفحه',
      spaceName: 'نام فضا',
      spaceKey: 'کلید فضا',
      spaceType: 'نوع فضا',
      workspaceSpace: 'فضای کاری',
      teamSpace: 'تیم',
      projectSpace: 'پروژه',
      spaceScopeDescription: 'فضا را برای کل فضای کاری، یک تیم یا یک پروژه بسازید.',
      selectTeam: 'تیم را انتخاب کنید',
      selectProject: 'پروژه را انتخاب کنید',
      pageTitle: 'عنوان صفحه',
      pageSummary: 'خلاصه',
      parentPage: 'صفحه مادر',
      rootPage: 'بدون صفحه مادر',
      contentPlaceholder: 'دانش، تصمیم، فرایند یا راهنمای قابل اتکا را بنویسید...',
      searchPlaceholder: 'جستجو در دانش‌نامه...',
      labels: 'برچسب‌ها',
      savedLabels: 'برچسب‌های ذخیره‌شده',
      labelsPlaceholder: 'برچسب‌ها را با ویرگول جدا کنید',
      owner: 'مالک',
      verified: 'تأییدشده',
      unverified: 'تأیید نشده',
      verify: 'تأیید',
      removeVerification: 'حذف تأیید',
      savePage: 'ذخیره صفحه',
      saving: 'در حال ذخیره...',
      saved: 'صفحه ذخیره شد.',
      createFailed: 'ایجاد صفحه ناموفق بود.',
      createSpaceFailed: 'ایجاد فضا ناموفق بود.',
      updateFailed: 'به‌روزرسانی صفحه ناموفق بود.',
      loadFailed: 'بارگذاری دانش‌نامه ناموفق بود.',
      noSpaces: 'هنوز فضایی برای دانش‌نامه ساخته نشده است.',
      noPages: 'در این فضا هنوز صفحه‌ای وجود ندارد.',
      noPageSelected: 'یک صفحه را انتخاب کنید یا صفحه تازه بسازید.',
      comments: 'دیدگاه‌ها',
      leaveComment: 'دیدگاه بنویسید...',
      commentCreated: 'دیدگاه ثبت شد.',
      commentFailed: 'ثبت دیدگاه ناموفق بود.',
      versions: 'نسخه‌ها',
      versionHistory: 'تاریخچه نسخه‌ها',
      revert: 'بازگردانی',
      reverted: 'نسخه بازگردانی شد.',
      archived: 'صفحه آرشیو شد.',
      archive: 'آرشیو',
      archiveConfirm: 'این صفحه آرشیو شود؟',
      createdAt: 'زمان ایجاد',
      updatedAt: 'آخرین تغییر',
      verificationUpdated: 'وضعیت تأیید به‌روزرسانی شد.',
      attachmentUploadFailed: 'بارگذاری تصویر ناموفق بود.',
   },
   heartbeat: {
      active: 'فعال',
      activeAssignedTasks: 'کار فعال',
      activeNow: 'فعال اکنون',
      activePastDue: 'فعال و گذشته از موعد',
      allTeams: 'همه تیم‌ها',
      allTime: 'همه زمان‌ها',
      atRisk: 'نیازمند توجه',
      blockedNow: 'مسدود اکنون',
      blockedOverdueStale: 'مسدود، دیرکرد یا بی‌حرکت',
      blockedShare: 'سهم انسداد',
      changedTasks: 'کارهای تغییرکرده',
      done: 'انجام‌شده',
      doneInWindow: 'انجام‌شده',
      doneShare: 'سهم انجام‌شده',
      doneTasks: 'انجام‌شده اخیر',
      doneTodayCount: (count: number) => `${count.toLocaleString('fa-IR')} کار امروز`,
      empty: 'هنوز کاری برای ساخت نبض تیم‌ها وجود ندارد.',
      inProgress: 'در جریان',
      inProgressTasks: 'در حال انجام',
      last: 'آخرین',
      latest: 'آخرین تغییر',
      needsAttention: 'نیازمند توجه',
      noDone: 'در این بازه کاری انجام نشده است.',
      noIdlePeople: 'شخصی بدون کار در حال انجام وجود ندارد.',
      noInProgress: 'کاری در جریان نیست.',
      noActiveAssignedTasks: 'بدون کار فعال',
      noOverdue: 'کاری از موعد گذشته نیست.',
      noRecentUpdates: 'در این بازه تغییری ثبت نشده است.',
      noRisks: 'ریسک فعالی دیده نمی‌شود.',
      noTeamData: 'داده‌ای برای این تیم‌ها وجود ندارد.',
      noUserDoneToday: 'امروز کاری انجام نداده است.',
      noWorkload: 'امروز کاری انجام نشده است.',
      onTrack: 'روان',
      overdue: 'گذشته از موعد',
      overdueNow: 'دیرکرد',
      quiet: 'کم‌تحرک',
      recentUpdates: 'آخرین به‌روزرسانی‌ها',
      refresh: 'به‌روزرسانی',
      risks: 'ریسک‌ها',
      stale: 'بی‌حرکت',
      startedOrReview: 'شروع‌شده یا در بازبینی',
      statusFlow: 'جریان وضعیت‌ها',
      statusFlowCaption: 'توزیع کارها در بک‌لاگ، در حال انجام، بازبینی، انسداد، انجام‌شده و لغوشده.',
      tasks: 'کار',
      teamHealth: 'سلامت تیم‌ها',
      teamFilter: 'فیلتر تیم',
      teams: 'تیم‌ها',
      unassignedTeam: 'بدون تیم',
      unassignedDoneTasks: 'انجام‌شده بدون مسئول',
      updated: 'به‌روزشده',
      updatedInWindow: 'به‌روزشده',
      watch: 'قابل پیگیری',
      workload: 'بار کاری',
      workInSystem: 'بک‌لاگ، انجام‌دادنی، در جریان و مسدود',
      withoutInProgress: 'بدون کار در حال انجام',
   },
   todayPlan: {
      capacityLabel: (limit: number) => `ظرفیت روزانه ${limit.toLocaleString('fa-IR')} وزن`,
      dueTasks: 'کارهای دارای سررسید امروز و قبل‌تر',
      noDueTasks: 'کاری برای امروز یا قبل‌تر ندارد.',
      noTasks: 'بدون کار',
      noUsers: 'کاربری برای نمایش برنامه امروز وجود ندارد.',
      noWeight: 'بدون وزن',
      overloadedPeople: 'افراد دارای اضافه‌بار',
      overloadBy: (value: number) => `${value.toLocaleString('fa-IR')} وزن اضافه‌بار`,
      peopleWorkload: 'برنامه امروز',
      taskCount: (count: number) => `${count.toLocaleString('fa-IR')} کار`,
      totalWeight: 'وزن کل کارهای امروز و قبل‌تر',
      unassignedTasks: 'کارهای بدون مسئول',
      weightOfLimit: (weight: number, limit: number) =>
         `${weight.toLocaleString('fa-IR')} از ${limit.toLocaleString('fa-IR')} وزن`,
   },
   issue: {
      all: 'همه کارها',
      active: 'فعال',
      backlog: 'بک‌لاگ',
      filters: 'فیلترها',
      display: 'نمایش',
      saveView: 'ذخیره نما',
      saveAsNewView: 'ذخیره به‌عنوان نمای جدید',
      updateView: 'به‌روزرسانی نما',
      deleteView: 'حذف نما',
      viewName: 'نام نما',
      sharedView: 'نمای مشترک',
      noSavedViews: 'هنوز نمای ذخیره‌شده‌ای وجود ندارد.',
      listView: 'فهرست',
      boardView: 'بورد',
      grouping: 'گروه‌بندی',
      ordering: 'مرتب‌سازی',
      showEmptyGroups: 'نمایش گروه‌های خالی',
      noGroupingValue: 'بدون مقدار',
      searchPlaceholder: 'جستجو در کارها...',
      noMatchingIssues: 'کاری مطابق این فیلترها پیدا نشد.',
      newIssue: 'کار جدید',
      titlePlaceholder: 'عنوان کار',
      descriptionPlaceholder: 'توضیح اضافه کنید...',
      status: 'وضعیت',
      priority: 'اولویت',
      weight: 'وزن',
      assignee: 'مسئول',
      assignmentAssistant: 'پیشنهاد مسئول',
      loadAssignmentRecommendations: 'پیشنهاد مسئول',
      refreshAssignmentRecommendations: 'به‌روزرسانی پیشنهادها',
      assignmentRecommendationFailed: 'دریافت پیشنهاد مسئول ناموفق بود.',
      noAssignmentRecommendations: 'پیشنهادی برای این کار پیدا نشد.',
      assignRecommendedUser: 'واگذاری',
      assignedRecommendedUser: 'کار به مسئول پیشنهادی واگذار شد.',
      assignmentReasonFallback: 'پیشنهاد بر اساس ظرفیت و کار فعال.',
      assignmentLoad: (weight: number, capacity: number) =>
         `${weight.toLocaleString('fa-IR')} از ${capacity.toLocaleString('fa-IR')} وزن بعد از واگذاری`,
      project: 'پروژه',
      review: 'بازبینی',
      reviewer: 'بازبین',
      requestReview: 'درخواست بازبینی',
      approveReview: 'تایید',
      requestChanges: 'درخواست تغییر',
      cancelReview: 'لغو بازبینی',
      reviewRequested: 'درخواست بازبینی ثبت شد.',
      reviewRequestFailed: 'ثبت درخواست بازبینی ناموفق بود.',
      reviewDecisionSaved: 'نتیجه بازبینی ثبت شد.',
      reviewDecisionFailed: 'ثبت نتیجه بازبینی ناموفق بود.',
      reviewCommentPlaceholder: 'یادداشت بازبینی...',
      requestedAt: 'زمان درخواست',
      relatedDocs: 'دانش مرتبط',
      noRelatedDocs: 'دانش مرتبطی ثبت نشده است.',
      labels: 'برچسب‌ها',
      labelsPlaceholder: 'برچسب‌ها را با ویرگول جدا کنید',
      dueAt: 'سررسید',
      dueAtPlaceholder: 'انتخاب سررسید',
      clearDueAt: 'حذف تاریخ سررسید',
      createMore: 'ادامه ساخت',
      createIssue: 'ایجاد کار',
      createFullscreen: 'نمای تمام‌صفحه',
      updateFailed: 'به‌روزرسانی کار ناموفق بود.',
      createFailed: 'ایجاد کار ناموفق بود.',
      deleteFailed: 'حذف کار ناموفق بود.',
      loadFailed: 'بارگذاری کارها ناموفق بود.',
      created: 'کار ایجاد شد.',
      createdOffline: 'کار ایجاد شد و پس از اتصال همگام‌سازی می‌شود.',
      openIssue: 'باز کردن کار',
      copyLink: 'کپی لینک',
      linkCopied: 'لینک کار کپی شد.',
      deleted: 'کار حذف شد.',
      deleteConfirm: 'این کار حذف شود؟',
      pendingSync: 'در انتظار همگام‌سازی',
      pendingAttachmentUpload: 'کار به‌صورت آفلاین ساخته شد. پس از همگام‌سازی، فایل‌ها را دوباره پیوست کنید.',
      titleRequired: 'عنوان کار الزامی است.',
      invalidWeight: 'وزن کار باید فقط یکی از مقادیر ۱، ۲، ۳، ۴ یا ۸ باشد.',
      projectRequired: 'برای ایجاد کار، ابتدا یک پروژه بسازید.',
      invalidDate: 'فرمت تاریخ جلالی نامعتبر است. از الگوی ۱۴۰۵/۰۲/۰۴ ۱۴:۳۰ استفاده کنید.',
      noIssuesInGroup: 'کاری در این گروه وجود ندارد.',
      noIssueSelected: 'یک کار را برای مشاهده جزئیات انتخاب کنید.',
      properties: 'ویژگی‌ها',
      triage: 'تریاژ ورودی',
      triageAccept: 'پذیرش',
      triageRequestInfo: 'اطلاعات',
      triageDecline: 'رد',
      triageReady: 'این کار آماده خروج از بک‌لاگ است.',
      triageNeedsPriority: 'برای پذیرش، ابتدا اولویت را مشخص کنید.',
      triageNeedsOwnerOrReason: 'برای پذیرش بدون مسئول، علت را ثبت کنید.',
      triageUnassignedReasonPlaceholder: 'علت پذیرش بدون مسئول...',
      triageCommentPlaceholder: 'یادداشت تریاژ...',
      triagePriorityRequired: 'برای پذیرش کار، اولویت را مشخص کنید.',
      triageAccepted: 'کار از بک‌لاگ پذیرفته شد.',
      triageInfoRequested: 'درخواست اطلاعات ثبت شد.',
      triageDeclined: 'کار رد شد.',
      triageActionFailed: 'اقدام تریاژ ناموفق بود.',
      activity: 'فعالیت',
      comments: 'نظرها',
      attachments: 'پیوست‌ها',
      uploadAttachment: 'افزودن پیوست',
      attachToDescription: 'افزودن سند به توضیح',
      attachToComment: 'افزودن سند به دیدگاه',
      dropAttachments: 'فایل‌ها را برای پیوست رها کنید',
      removeAttachment: 'حذف پیوست',
      attachmentUploadFailed: 'بارگذاری پیوست ناموفق بود.',
      attachmentUploaded: 'پیوست اضافه شد.',
      attachmentsUploaded: '{count} پیوست اضافه شد.',
      noActivity: 'فعالیتی برای این کار ثبت نشده است.',
      commentFailed: 'ثبت دیدگاه ناموفق بود.',
      commentCreated: 'دیدگاه ثبت شد.',
      moreActions: 'اقدام‌های بیشتر',
      sendTaskSms: 'ارسال پیامک کار',
      sendTaskFollowUpSms: 'ارسال پیامک پیگیری کار',
      smsSent: 'پیامک کار ارسال شد.',
      smsFollowUpSent: 'پیامک پیگیری کار ارسال شد.',
      smsFailed: 'ارسال پیامک ناموفق بود.',
      smsNoAssignee: 'این کار مسئول ندارد.',
      smsNoPhone: 'شماره موبایل مسئول ثبت نشده است.',
      subtasks: 'زیرکارها',
      dependencies: 'وابستگی‌ها',
      addSubIssues: 'افزودن زیرکار',
      leaveComment: 'دیدگاه بنویسید...',
      details: 'جزئیات کار',
      createdAt: 'زمان ایجاد',
      updatedAt: 'آخرین تغییر',
      currentUser: 'کاربر فعلی',
      noAssignee: 'بدون مسئول',
   },
   sync: {
      mutationQueued: 'تغییر ذخیره شد و پس از اتصال دوباره اعمال می‌شود.',
      mutationConflict: (action: string) =>
         `${action} اعمال نشد، چون داده روی سرور تغییر کرده است. صفحه را به‌روزرسانی کنید و دوباره تصمیم بگیرید.`,
      mutationPending: (action: string) =>
         `${action} هنوز در صف همگام‌سازی است. اگر چند دقیقه دیگر باقی ماند، صفحه را به‌روزرسانی کنید.`,
      mutationRejected: (action: string) =>
         `${action} اعمال نشد. دسترسی، وضعیت یا داده مرتبط تغییر کرده است؛ صفحه را به‌روزرسانی کنید و دوباره بررسی کنید.`,
      mutationValidationFailed: (action: string) =>
         `${action} اعمال نشد، چون داده ارسالی معتبر نیست. مقدارها را بررسی کنید و دوباره تلاش کنید.`,
      mutationFailureSummary: (count: number) =>
         `${count.toLocaleString('fa-IR')} تغییر همگام‌سازی اعمال نشد.`,
   },
   announcement: {
      title: 'اعلان‌ها',
      newAnnouncement: 'اعلان جدید',
      titlePlaceholder: 'عنوان اعلان',
      bodyPlaceholder: 'متن اعلان را بنویسید...',
      recipients: 'مخاطبان',
      addPoll: 'افزودن نظرسنجی',
      pollQuestion: 'سؤال نظرسنجی',
      pollQuestionPlaceholder: 'مثلاً کدام زمان برای جلسه مناسب‌تر است؟',
      pollOptionPlaceholder: 'گزینه {index}',
      pollAddOption: 'افزودن گزینه',
      pollAllowMultiple: 'امکان انتخاب چندگزینه‌ای',
      pollVote: 'ثبت رأی',
      pollVoting: 'در حال ثبت رأی...',
      pollVoteSaved: 'رأی شما ثبت شد.',
      pollVoteFailed: 'ثبت رأی ناموفق بود.',
      pollRequiresTwoOptions: 'نظرسنجی حداقل به دو گزینه نیاز دارد.',
      pollQuestionRequired: 'سؤال نظرسنجی الزامی است.',
      pollDuplicateOption: 'گزینه‌های نظرسنجی باید یکتا باشند.',
      pollVotesCount: '{count} رأی',
      pollYourVote: 'انتخاب شما',
      draft: 'پیش‌نویس',
      published: 'منتشرشده',
      archived: 'آرشیوشده',
      create: 'ایجاد اعلان',
      saveDraft: 'ذخیره پیش‌نویس',
      publish: 'انتشار',
      publishDraft: 'انتشار پیش‌نویس',
      publishDraftHint: 'برای انتشار، مخاطبان را انتخاب کنید. بعد از انتشار، اعلان در صندوق ورودی مخاطبان قرار می‌گیرد.',
      publishDraftNoRecipients: 'برای انتشار حداقل یک مخاطب لازم است.',
      publishedToast: 'اعلان منتشر شد.',
      markRead: 'خواندم',
      read: 'خوانده شده',
      sendSms: 'ارسال پیامک اعلان',
      smsSent: 'پیامک اعلان ارسال شد.',
      smsSummary: 'ارسال‌شده: {sent}، بدون شماره: {skipped}، ناموفق: {failed}',
      loadFailed: 'بارگذاری اعلان‌ها ناموفق بود.',
      createFailed: 'ایجاد اعلان ناموفق بود.',
      updateFailed: 'به‌روزرسانی اعلان ناموفق بود.',
      smsFailed: 'ارسال پیامک اعلان ناموفق بود.',
      noAnnouncements: 'اعلانی برای نمایش وجود ندارد.',
      selectAnnouncement: 'یک اعلان را انتخاب کنید.',
      unread: 'خوانده‌نشده',
   },
   communications: {
      title: 'اعلان‌ها',
      announcementType: 'اعلان‌ها',
      all: 'همه',
      mine: 'برای من',
      actions: 'اقدام‌ها',
      sms: 'ارسال پیامک',
      createPrimary: 'ایجاد اعلان یا جلسه',
      linkedTasks: 'کارهای ساخته‌شده',
      loadFailed: 'بارگذاری اعلان‌ها و جلسه‌ها ناموفق بود.',
      noItems: 'اعلان یا جلسه‌ای برای نمایش وجود ندارد.',
      noSearchResults: 'نتیجه‌ای برای این جستجو پیدا نشد.',
      searchPlaceholder: 'جستجو در اعلان‌ها و جلسه‌ها...',
      selectItem: 'یک اعلان یا جلسه را انتخاب کنید.',
      peopleCount: (count: number) => `${count.toLocaleString('fa-IR')} نفر`,
      ownerLine: (name: string) => `مسئول: ${name}`,
   },
   meeting: {
      title: 'جلسه‌ها',
      newMeeting: 'جلسه جدید',
      titlePlaceholder: 'عنوان جلسه',
      descriptionPlaceholder: 'دستور جلسه یا صورت‌جلسه را بنویسید...',
      participants: 'شرکت‌کننده‌ها',
      owner: 'مسئول جلسه',
      project: 'پروژه',
      team: 'تیم',
      scheduledAt: 'زمان جلسه',
      status: 'وضعیت',
      planned: 'برنامه‌ریزی‌شده',
      held: 'برگزارشده',
      canceled: 'لغوشده',
      archived: 'آرشیوشده',
      create: 'ایجاد جلسه',
      createTasks: 'ساخت کار از جلسه',
      actionItems: 'کارهای خروجی',
      actionTitlePlaceholder: 'عنوان کار خروجی',
      sendSms: 'ارسال پیامک جلسه',
      smsSent: 'پیامک جلسه ارسال شد.',
      smsSummary: 'ارسال‌شده: {sent}، بدون شماره: {skipped}، ناموفق: {failed}',
      loadFailed: 'بارگذاری جلسه‌ها ناموفق بود.',
      createFailed: 'ایجاد جلسه ناموفق بود.',
      updateFailed: 'به‌روزرسانی جلسه ناموفق بود.',
      taskCreateFailed: 'ساخت کارهای جلسه ناموفق بود.',
      smsFailed: 'ارسال پیامک جلسه ناموفق بود.',
      noMeetings: 'جلسه‌ای برای نمایش وجود ندارد.',
      selectMeeting: 'یک جلسه را انتخاب کنید.',
   },
   project: {
      all: 'همه پروژه‌ها',
      active: 'فعال',
      newProject: 'پروژه جدید',
      unassignedProjects: 'پروژه‌های بدون تیم',
      addToTeam: 'افزودن به تیم',
      teamUpdated: 'تیم پروژه به‌روزرسانی شد.',
      teamUpdateFailed: 'به‌روزرسانی تیم پروژه ناموفق بود.',
      namePlaceholder: 'نام پروژه',
      summaryPlaceholder: 'خلاصه کوتاه اضافه کنید...',
      descriptionPlaceholder: 'توضیح، طرح پروژه، یا ایده‌ها را بنویسید...',
      keyPrefix: 'کلید پروژه',
      keyPrefixPlaceholder: 'CORE',
      status: 'وضعیت',
      lead: 'مسئول پروژه',
      team: 'تیم',
      members: 'اعضا',
      start: 'شروع',
      target: 'هدف',
      labels: 'برچسب‌ها',
      dependencies: 'وابستگی‌ها',
      milestones: 'مایلستون‌ها',
      docs: 'دانش پروژه',
      createDocs: 'ساخت دانش',
      docsCreated: 'فضای دانش پروژه ساخته شد.',
      docsCreateFailed: 'ساخت فضای دانش پروژه ناموفق بود.',
      health: 'سلامت',
      healthUpdate: 'آپدیت سلامت',
      createHealthUpdate: 'ثبت آپدیت',
      publishHealthUpdate: 'انتشار در متراست',
      republishHealthUpdate: 'انتشار دوباره',
      healthUpdateFor: (name: string) => `آپدیت سلامت ${name}`,
      healthUpdateDescription: 'وضعیت، پیشرفت، ریسک‌ها و تصمیم‌های لازم را کوتاه و قابل پیگیری ثبت کنید.',
      healthOnTrack: 'طبق برنامه',
      healthAtRisk: 'در ریسک',
      healthOffTrack: 'خارج از مسیر',
      nextUpdateDue: 'آپدیت بعدی',
      noHealthUpdate: 'هنوز آپدیت سلامت ثبت نشده است.',
      healthSummaryPlaceholder: 'خلاصه وضعیت فعلی پروژه...',
      healthProgressPlaceholder: 'پیشرفت مهم از آپدیت قبلی...',
      healthRisksPlaceholder: 'ریسک‌ها یا موانع...',
      healthDecisionsPlaceholder: 'تصمیم‌های لازم از مدیر...',
      healthSummaryRequired: 'خلاصه آپدیت سلامت الزامی است.',
      healthUpdateCreated: 'آپدیت سلامت پروژه ثبت شد.',
      healthUpdateQueued: 'آپدیت سلامت ذخیره شد و بعد از اتصال اعمال می‌شود.',
      healthUpdateFailed: 'ثبت آپدیت سلامت ناموفق بود.',
      healthUpdatePublished: 'آپدیت سلامت در متراست منتشر شد.',
      healthPublishNoBinding: 'برای این پروژه کانال متراست وصل نشده است؛ آپدیت ذخیره شد.',
      healthPublishNoConfig: 'تنظیمات بات متراست کامل نیست؛ آپدیت ذخیره شد.',
      healthPublishFailed: 'انتشار آپدیت سلامت ناموفق بود.',
      noHealthUpdateToPublish: 'برای انتشار، ابتدا آپدیت سلامت ثبت کنید.',
      createProject: 'ایجاد پروژه',
      createFailed: 'ایجاد پروژه ناموفق بود.',
      loadFailed: 'بارگذاری پروژه‌ها ناموفق بود.',
      created: 'پروژه ایجاد شد.',
      nameRequired: 'نام و کلید پروژه الزامی است.',
      list: 'فهرست پروژه‌ها',
      issueCount: 'تعداد کار',
      noProjects: 'هنوز پروژه‌ای ثبت نشده است.',
   },
   milestone: {
      title: 'مایلستون‌ها',
      newMilestone: 'مایلستون جدید',
      create: 'ایجاد مایلستون',
      createFeature: 'ساخت مایلستون ویژگی',
      createPhase: 'ساخت مایلستون فاز',
      createDescription: 'یک هدف قابل اندازه‌گیری برای تحویل ویژگی یا پایان یک فاز پروژه تعریف کنید.',
      name: 'نام',
      namePlaceholder: 'مثلاً آماده‌سازی نسخه عمومی',
      description: 'توضیح',
      descriptionPlaceholder: 'نتیجه مورد انتظار، مرز دامنه و معیار پایان را بنویسید…',
      project: 'پروژه',
      selectProject: 'پروژه را انتخاب کنید',
      kind: 'نوع',
      feature: 'ویژگی',
      phase: 'فاز اجرا',
      other: 'سایر',
      status: 'وضعیت',
      planned: 'برنامه‌ریزی‌شده',
      active: 'فعال',
      completed: 'تکمیل‌شده',
      canceled: 'لغوشده',
      open: 'باز',
      all: 'همه',
      archived: 'آرشیوشده',
      includeArchived: 'نمایش آرشیوشده‌ها',
      owner: 'مالک',
      noOwner: 'بدون مالک',
      health: 'سلامت',
      healthOnTrack: 'طبق برنامه',
      healthAtRisk: 'در ریسک',
      healthOffTrack: 'خارج از مسیر',
      noHealth: 'سلامت تعیین نشده',
      startDate: 'تاریخ شروع',
      targetDate: 'تاریخ هدف',
      noTarget: 'بدون تاریخ هدف',
      progressiveFields: 'جزئیات بیشتر',
      searchPlaceholder: 'جستجوی مایلستون…',
      filters: 'فیلترها',
      clearFilters: 'پاک‌کردن فیلترها',
      team: 'تیم',
      type: 'نوع',
      overdueOnly: 'فقط عقب‌افتاده‌ها',
      noMilestones: 'هنوز مایلستونی ساخته نشده است.',
      noMilestone: 'بدون مایلستون',
      noMilestonesDescription: 'مایلستون برای یک ویژگی یا فاز اجرایی است؛ اقدام‌های اجرایی را به‌صورت کار به آن متصل کنید.',
      noFilteredResults: 'مایلستونی با این فیلترها پیدا نشد.',
      selectMilestone: 'یک مایلستون را برای مشاهده جزئیات انتخاب کنید.',
      noAccess: 'این مایلستون در دسترس نیست یا دسترسی شما به پروژه آن تغییر کرده است.',
      loadingFailed: 'بارگذاری مایلستون‌ها ناموفق بود.',
      detailLoadingFailed: 'بارگذاری جزئیات مایلستون ناموفق بود.',
      created: 'مایلستون ساخته شد.',
      createFailed: 'ایجاد مایلستون ناموفق بود. اطلاعات شما حفظ شده است.',
      updated: 'مایلستون به‌روز شد.',
      updateFailed: 'به‌روزرسانی مایلستون ناموفق بود.',
      versionConflict: 'این مایلستون جای دیگری تغییر کرده است. آخرین نسخه بارگذاری شد.',
      conflictDraftRetained: 'پیش‌نویس شما حفظ شده است؛ پس از بررسی نسخه تازه، دوباره ذخیره کنید.',
      duplicateName: 'مایلستونی با همین نام در این پروژه وجود دارد.',
      invalidDates: 'تاریخ هدف نمی‌تواند قبل از تاریخ شروع باشد.',
      nameRequired: 'نام، پروژه و نوع مایلستون الزامی است.',
      overview: 'نمای کلی',
      work: 'کارها',
      activity: 'فعالیت',
      progress: 'پیشرفت',
      noTasks: 'هنوز کاری به این مایلستون متصل نیست.',
      noTasksDescription: 'یک کار تازه بسازید یا کارهای موجود همین پروژه را افزوده کنید.',
      createTask: 'ساخت کار',
      addExistingTasks: 'افزودن کارهای موجود',
      addTasksDescription: 'فقط کارهای همین پروژه قابل افزودن هستند.',
      addSelectedTasks: 'افزودن کارهای انتخابی',
      tasksAdded: 'کارهای انتخابی افزوده شدند.',
      tasksAddFailed: 'افزودن برخی از کارها ناموفق بود.',
      removeTask: 'حذف از مایلستون',
      taskRemoved: 'کار از مایلستون جدا شد.',
      taskRemoveFailed: 'جدا کردن کار ناموفق بود.',
      tasksSearchPlaceholder: 'جستجو در کارهای این مایلستون…',
      noActivity: 'هنوز فعالیتی ثبت نشده است.',
      attention: 'نیازمند توجه',
      noAttention: 'بدون هشدار',
      overdue: 'از تاریخ هدف گذشته است',
      blockedTasks: 'کار مسدود',
      overdueTasks: 'کار عقب‌افتاده',
      missingOwner: 'مالک تعیین نشده',
      missingTarget: 'تاریخ هدف تعیین نشده',
      readyToComplete: 'آماده تکمیل',
      noEligibleTasks: 'بدون کار',
      progressCount: (completed: number, total: number) => `${completed.toLocaleString('fa-IR')} از ${total.toLocaleString('fa-IR')} کار`,
      blockedCount: (count: number) => `${count.toLocaleString('fa-IR')} کار مسدود`,
      overdueCount: (count: number) => `${count.toLocaleString('fa-IR')} کار عقب‌افتاده`,
      taskCount: (count: number) => `${count.toLocaleString('fa-IR')} کار`,
      activate: 'فعال‌کردن',
      complete: 'تکمیل',
      reopen: 'بازگشایی',
      reactivate: 'فعال‌کردن دوباره',
      cancelMilestone: 'لغو مایلستون',
      archive: 'آرشیو',
      restore: 'بازگردانی',
      lifecycleActionFailed: 'تغییر وضعیت مایلستون ناموفق بود.',
      lifecycleUpdated: 'وضعیت مایلستون به‌روز شد.',
      completeTitle: 'تکمیل مایلستون',
      cancelTitle: 'لغو مایلستون',
      finishDescription: 'وضعیت کارها با این اقدام تغییر نمی‌کند.',
      unfinishedTasks: 'کارهای ناتمام',
      chooseUnfinishedPolicy: 'برای کارهای ناتمام یک تصمیم صریح انتخاب کنید.',
      keepTasks: 'نگه‌داشتن در این مایلستون',
      keepTasksDescription: 'پیوند کارها برای سابقه و پیگیری باقی می‌ماند.',
      moveTasks: 'انتقال به مایلستون دیگر',
      moveTasksDescription: 'همه کارهای ناتمام به یک مایلستون باز از همین پروژه می‌روند.',
      unassignTasks: 'بازگرداندن به بدون مایلستون',
      unassignTasksDescription: 'پیوند مایلستون از کارهای ناتمام برداشته می‌شود.',
      targetMilestone: 'مایلستون مقصد',
      completionNote: 'یادداشت پایان اختیاری',
      completionNotePlaceholder: 'نتیجه، آموخته‌ها یا علت لغو را کوتاه ثبت کنید…',
      archiveDescription: 'مایلستون از فهرست عادی خارج می‌شود، اما پیوند کارها و سابقه حفظ می‌شود.',
      readOnlyArchived: 'این مایلستون آرشیوشده و فقط قابل مشاهده است. برای ویرایش آن را بازگردانید.',
      saved: 'ذخیره شد',
      saving: 'در حال ذخیره…',
      retry: 'تلاش دوباره',
   },
   inbox: {
      notifications: 'اعلان‌ها',
      unread: 'خوانده‌نشده',
      markAllRead: 'خواندن همه',
      markRead: 'علامت‌گذاری به عنوان خوانده‌شده',
      noNotifications: 'اعلانی برای کارهای دنبال‌شده، واگذاری‌ها یا منشن‌های شما وجود ندارد.',
      noDescription: 'این اعلان توضیح تکمیلی ندارد.',
      selectNotification: 'یک اعلان را برای مشاهده جزئیات انتخاب کنید.',
      loadFailed: 'بارگذاری صندوق ورودی ناموفق بود.',
      markAllFailed: 'علامت‌گذاری همه اعلان‌ها ناموفق بود.',
      registeredAt: 'زمان ثبت',
      type: 'نوع اعلان',
   },
   command: {
      title: 'منوی فرمان',
      description: 'مسیرها و عملیات تسکارا را اجرا کنید.',
      createIssue: 'ایجاد کار',
      createIssueDescription: 'باز کردن فرم ساخت کار',
      createProject: 'ایجاد پروژه',
      createProjectDescription: 'باز کردن فرم ساخت پروژه',
      goAllTasks: 'رفتن به همه کارها',
      goIssues: 'رفتن به کارها',
      goInbox: 'رفتن به صندوق ورودی',
      goProjects: 'رفتن به پروژه‌ها',
      goMilestones: 'رفتن به مایلستون‌ها',
      createMilestone: 'ایجاد مایلستون',
      createMilestoneDescription: 'تعریف یک ویژگی یا فاز اجرایی برای پروژه',
      goWiki: 'رفتن به دانش‌نامه',
      goTeamHealth: 'رفتن به سلامت تیم‌ها',
      goReviews: 'بازبینی‌های من',
      goPeopleWorkload: 'بررسی بار افراد',
      goCapacitySettings: 'تنظیم ظرفیت و توافق‌ها',
      goHeartbeat: 'رفتن به نبض تیم‌ها',
      goTodayPlan: 'رفتن به برنامه امروز',
      goMembers: 'رفتن به اعضا',
      goTeams: 'رفتن به تیم‌ها',
      goCockpit: 'رفتن به میز مدیر',
      goDecisionQueues: 'تصمیم‌های امروز',
      goSettings: 'رفتن به تنظیمات',
   },
   reviews: {
      loadFailed: 'بارگذاری بازبینی‌ها ناموفق بود.',
      description: 'بازبینی‌هایی که تصمیم شما جریان کار را جلو می‌برد.',
      visibleCount: (count: number) => `${count.toLocaleString('fa-IR')} بازبینی`,
      requested: 'در انتظار من',
      all: 'همه',
      refresh: 'به‌روزرسانی',
      pendingMetric: 'منتظر تصمیم',
      overdueMetric: 'عبور از SLA',
      changesMetric: 'نیازمند اصلاح',
      doneMetric: 'بسته‌شده',
      requestedTitle: 'بازبینی‌های باز',
      allTitle: 'همه بازبینی‌های من',
      requestedDescription: 'مواردی که هنوز باید تأیید، اصلاح‌خواهی یا لغو شوند.',
      allDescription: 'تاریخچه تصمیم‌های بازبینی شما در کنار موارد باز.',
      decisionFailed: 'ثبت تصمیم بازبینی ناموفق بود.',
      decisionTitle: 'تصمیم بازبینی',
      decisionDescription: 'نظر کوتاه برای ثبت در جریان کار بنویسید.',
      commentPlaceholder: 'دلیل تصمیم یا اصلاح موردنیاز را کوتاه بنویسید...',
      missingTask: 'کار مرتبط در دسترس نیست',
      requester: (name: string) => `درخواست‌دهنده: ${name}`,
      requestedAt: (date: string) => `درخواست: ${date}`,
      dueAt: (date: string) => `SLA: ${date}`,
      openTask: 'باز کردن کار',
      approve: 'تایید',
      requestChanges: 'درخواست اصلاح',
      cancelReview: 'لغو بازبینی',
      emptyTitle: 'بازبینی بازی برای شما نیست.',
      emptyDescription: 'وقتی کاری برای تأیید یا بازگشت به اصلاح به شما سپرده شود اینجا ظاهر می‌شود.',
      statusRequested: 'در انتظار',
      statusChangesRequested: 'اصلاح خواسته شد',
      statusApproved: 'تایید شد',
      statusCanceled: 'لغو شد',
      approveTitle: 'تایید بازبینی',
      approveDescription: 'این تصمیم کار را به انجام‌شده منتقل می‌کند و requester را مطلع می‌کند.',
      requestChangesTitle: 'درخواست اصلاح',
      requestChangesDescription: 'این تصمیم کار را به جریان اجرا برمی‌گرداند و اصلاح موردنیاز را ثبت می‌کند.',
      cancelTitle: 'لغو بازبینی',
      cancelDescription: 'این تصمیم درخواست بازبینی را می‌بندد و کار را از صف بازبینی خارج می‌کند.',
      approvedToast: 'بازبینی تایید شد.',
      changesRequestedToast: 'درخواست اصلاح ثبت شد.',
      canceledToast: 'بازبینی لغو شد.',
   },
   peopleWorkload: {
      loadFailed: 'بارگذاری بار افراد ناموفق بود.',
      description: 'افراد را بر اساس فشار ظرفیت، موانع، بازبینی و نیاز به هماهنگی پیگیری کنید.',
      generatedAt: 'آخرین محاسبه',
      refresh: 'به‌روزرسانی',
      truncated: 'فضای کاری بزرگ است؛ داده‌های افراد و کارها محدود شده‌اند.',
      all: 'همه',
      risk: 'نیازمند پیگیری',
      overloaded: 'فشار بالا',
      blocked: 'مانع',
      review: 'بازبینی',
      idle: 'بدون برنامه',
      peopleMetric: 'افراد',
      overloadedMetric: 'فشار بالا',
      blockedMetric: 'دارای مانع',
      reviewMetric: 'درگیر بازبینی',
      missingCheckInMetric: 'چک‌این عقب‌افتاده',
      active: 'فعال',
      today: 'امروز',
      capacity: 'ظرفیت',
      activeTasks: 'کارهای فعلی',
      noActiveTasks: 'کار فعالی برای این فرد دیده نمی‌شود.',
      noPeople: 'فردی برای نمایش وجود ندارد.',
      noPeopleDescription: 'وقتی کار فعال، ظرفیت یا چک‌این وارد شود این صفحه به نمای پیگیری افراد تبدیل می‌شود.',
      noFilteredPeople: 'موردی با این فیلتر دیده نمی‌شود.',
      noFilteredPeopleDescription: 'فیلتر دیگری انتخاب کنید یا بعد از ورود کارهای جدید دوباره بررسی کنید.',
      assignTask: 'واگذاری کار',
      scheduleSync: 'برنامه sync',
      createOneOnOne: 'ساخت ۱:۱',
      openOneOnOne: 'باز کردن ۱:۱',
      requestCheckIn: 'درخواست چک‌این',
      copiedCheckInRequest: 'متن درخواست چک‌این آماده شد.',
      checkInCopyFailed: 'کپی خودکار ممکن نبود؛ متن درخواست را دستی ارسال کنید.',
      oneOnOneCreated: '۱:۱ ساخته شد.',
      oneOnOneQueued: 'ساخت ۱:۱ ذخیره شد و بعد از اتصال اعمال می‌شود.',
      oneOnOneFailed: 'ساخت ۱:۱ ناموفق بود.',
      oneOnOneDue: '۱:۱ نزدیک',
      missingCheckIn: 'چک‌این عقب‌افتاده',
      noCheckInYet: 'بدون چک‌این',
      checkInAge: (hours: number) => `${hours.toLocaleString('fa-IR')} ساعت از آخرین چک‌این`,
      nextOneOnOne: (date: string) => `۱:۱ بعدی: ${date}`,
      capacityLoad: (weight: number, capacity: number) =>
         `${weight.toLocaleString('fa-IR')} از ${capacity.toLocaleString('fa-IR')} وزن`,
      todayLoad: (weight: number) => `${weight.toLocaleString('fa-IR')} وزن امروز`,
      taskCount: (count: number) => `${count.toLocaleString('fa-IR')} کار`,
      checkInRequestText: (name: string) =>
         `${name} سلام، لطفا چک‌این امروزت را با برنامه بعدی، مانع‌ها و جایی که کمک لازم داری در تسکارا ثبت کن.`,
   },
   capacitySettings: {
      activeCapacity: 'فعال در ظرفیت',
      activeCapacityDescription: 'غیرفعال‌ها در سیگنال بی‌برنامه و پیشنهاد واگذاری کمتر ظاهر می‌شوند.',
      activeMetric: 'ظرفیت فعال',
      activeWipLimit: 'حد WIP فعال',
      agreementDescription: 'توافق‌های کاری منبع آستانه‌های سلامت، بازبینی، انسداد و رکود هستند.',
      agreementSaved: 'توافق کاری ذخیره شد.',
      agreementTitle: 'توافق کاری',
      averageMetric: 'میانگین ظرفیت روزانه',
      blockedSlaHours: 'SLA انسداد (ساعت)',
      capacitySaved: 'ظرفیت ذخیره شد.',
      dailyLimit: 'ظرفیت روزانه',
      defaultCapacity: 'پیش‌فرض',
      description: 'این تنظیمات فقط آستانه‌ها را تعریف می‌کند؛ محاسبه فشار و پیشنهاد واگذاری همچنان در backend انجام می‌شود.',
      invalidAgreement: 'مقادیر توافق کاری معتبر نیستند.',
      invalidCapacity: 'مقادیر ظرفیت معتبر نیستند.',
      loadFailed: 'بارگذاری ظرفیت و توافق‌ها ناموفق بود.',
      noUsers: 'عضوی برای تنظیم ظرفیت وجود ندارد.',
      note: 'یادداشت ظرفیت',
      notePlaceholder: 'مثلا پاره‌وقت، مرخصی، تمرکز روی پشتیبانی یا ظرفیت محدود این هفته...',
      optionalNumber: 'اختیاری',
      peopleMetric: 'اعضا',
      refresh: 'به‌روزرسانی',
      reviewSlaHours: 'SLA بازبینی (ساعت)',
      reviewWipLimit: 'حد WIP بازبینی',
      saveAgreement: 'ذخیره توافق',
      saveCapacity: 'ذخیره ظرفیت',
      saveFailed: 'ذخیره تنظیمات ظرفیت ناموفق بود.',
      scope: 'دامنه توافق',
      staleAfterHours: 'رکود بعد از (ساعت)',
      userCapacityDescription: 'ظرفیت هر نفر بر اساس وزن کار است، نه تعداد خام کارها.',
      userCapacityTitle: 'ظرفیت افراد',
      weeklyLimit: 'ظرفیت هفتگی',
      weightUnit: 'وزن',
      workspaceScope: 'کل فضای کاری',
   },
   decisionQueues: {
      loadFailed: 'بارگذاری تصمیم‌های امروز ناموفق بود.',
      description: 'صف‌های عملیاتی که امروز نیاز به تصمیم مدیر دارند.',
      generatedAt: 'آخرین محاسبه',
      refresh: 'به‌روزرسانی',
      truncated: 'داده‌ها محدود شده‌اند؛ صف‌ها بر اساس اولویت کوتاه شده‌اند.',
      reviewQueue: 'بازبینی',
      backlogQueue: 'تریاژ بک‌لاگ',
      unassignedQueue: 'بی‌مسئول',
      blockedQueue: 'مسدود',
      peopleQueue: 'افراد نیازمند پیگیری',
      reviewTitle: 'صف بازبینی',
      reviewDescription: 'کارهایی که منتظر بازبین هستند یا از SLA بازبینی فاصله گرفته‌اند.',
      reviewAction: 'بازبینی',
      triageTitle: 'تریاژ ورودی',
      triageDescription: 'کارهای بک‌لاگ که باید پذیرفته، روشن، رد، تکراری یا تقسیم شوند.',
      triageAction: 'تصمیم تریاژ',
      triageAccept: 'پذیرش',
      triageAcceptTitle: 'پذیرش ورودی',
      triageAcceptConfirm: 'ثبت پذیرش',
      triageCanonicalTask: 'کار اصلی',
      triageCommentPlaceholder: 'یادداشت اختیاری برای تصمیم پذیرش...',
      triageDecline: 'رد',
      triageDeclineConfirm: 'ثبت رد',
      triageDeclinePlaceholder: 'علت رد شدن این ورودی...',
      triageDeclineTitle: 'رد ورودی',
      triageDuplicate: 'تکراری',
      triageDuplicateConfirm: 'ثبت تکراری',
      triageDuplicatePlaceholder: 'علت یا زمینه تکراری بودن...',
      triageDuplicateRequired: 'کار اصلی تکراری را وارد کنید.',
      triageDuplicateTitle: 'ثبت تکراری',
      triageDuplicated: 'کار به عنوان تکراری بسته شد.',
      triageMore: 'جزئیات',
      triageNoteRequired: 'یادداشت این تصمیم باید حداقل ۳ کاراکتر باشد.',
      triageOptionalNote: 'یادداشت اختیاری',
      triagePriority: 'اولویت اجرا',
      triageRequestInfo: 'اطلاعات',
      triageRequestInfoConfirm: 'ثبت درخواست',
      triageRequestInfoPlaceholder: 'چه اطلاعاتی برای تصمیم تریاژ کم است؟',
      triageRequestInfoTitle: 'درخواست اطلاعات',
      triageRequiredNote: 'یادداشت تصمیم',
      triageSnooze: 'تعویق',
      triageSnoozeConfirm: 'ثبت تعویق',
      triageSnoozePlaceholder: 'چرا این ورودی فعلا از صف تصمیم خارج می‌شود؟',
      triageSnoozeRequired: 'زمان تعویق باید در آینده باشد.',
      triageSnoozeTitle: 'تعویق ورودی',
      triageSnoozed: 'ورودی تریاژ تعویق شد.',
      triageSnoozedUntil: 'تعویق تا',
      triageSplit: 'تقسیم',
      triageSplitAdd: 'افزودن مورد',
      triageSplitConfirm: 'ثبت تقسیم',
      triageSplitDescription: 'توضیح اختیاری برای این مورد...',
      triageSplitItems: 'کارهای جدید',
      triageSplitReasonPlaceholder: 'چرا این ورودی به چند کار تقسیم می‌شود؟',
      triageSplitRemove: 'حذف مورد',
      triageSplitRequired: 'برای تقسیم، حداقل دو عنوان کار جدید لازم است.',
      triageSplitSaved: 'ورودی به کارهای کوچک‌تر تقسیم شد.',
      triageSplitTitle: (index: number) => `عنوان کار ${index.toLocaleString('fa-IR')}`,
      triageSplitTitleDialog: 'تقسیم ورودی',
      triageUnassignedReasonPlaceholder: 'علت پذیرش بدون مسئول...',
      unassignedTitle: 'واگذاری و مالکیت',
      unassignedDescription: 'کارهای فعال یا نزدیک به موعد که هنوز مسئول روشن ندارند.',
      assignAction: 'واگذاری',
      blockedTitle: 'انسداد و دیرکرد',
      blockedDescription: 'کارهایی که با رفع مانع یا تصمیم فوری جریان تیم را باز می‌کنند.',
      unblockAction: 'رفع مانع',
      staleTitle: 'کارهای راکد',
      staleDescription: 'کارهایی که مدت زیادی بدون تغییر مانده‌اند و نیاز به پیگیری دارند.',
      staleAction: 'پیگیری',
      peopleTitle: 'پیگیری افراد',
      peopleDescription: 'افرادی که به دلیل فشار، انسداد، دیرکرد یا صف بازبینی به هماهنگی نیاز دارند.',
      noReviews: 'بازبینی قابل پیگیری وجود ندارد.',
      noTriage: 'ورودی تازه‌ای برای تریاژ نیست.',
      noUnassigned: 'کار بی‌مسئول قابل پیگیری وجود ندارد.',
      noBlocked: 'انسداد یا دیرکرد فعالی در محدوده قابل مشاهده نیست.',
      noStale: 'کار راکد قابل توجهی دیده نمی‌شود.',
      noPeople: 'فردی با فشار یا مانع قابل پیگیری دیده نمی‌شود.',
      emptyTitle: 'صف تصمیم فعالی وجود ندارد.',
      emptyDescription: 'وقتی بازبینی، ورودی، انسداد یا فشار ظرفیت ایجاد شود این صفحه به صف تصمیم مدیر تبدیل می‌شود.',
      noAssignee: 'بی‌مسئول',
      reviewer: (name: string) => `بازبین: ${name}`,
      reviewerUnknown: 'بازبین نامشخص',
      waitingSince: (date: string) => `از ${date}`,
      dueAt: (date: string) => `موعد: ${date}`,
      active: 'فعال',
      review: 'بازبینی',
      blocked: 'مسدود',
      overdue: 'دیرکرد',
      capacity: 'ظرفیت',
      load: (weight: number, capacity: number) =>
         `${weight.toLocaleString('fa-IR')} از ${capacity.toLocaleString('fa-IR')} وزن`,
   },
   cockpit: {
      loadFailed: 'بارگذاری میز مدیر ناموفق بود.',
      refresh: 'به‌روزرسانی',
      queueCount: (count: number, hasMore = false) =>
         `${hasMore ? 'حداقل ' : ''}${count.toLocaleString('fa-IR')} مورد باز`,
      singleQueueDescription: 'همه سیگنال‌های کار، افراد، جلسه‌ها و پروژه‌ها در یک صف اولویت‌بندی‌شده؛ هر بار فقط مورد بعدی را تعیین تکلیف کنید.',
      nextAction: 'اقدام بعدی',
      remainingActions: 'بعد از این',
      showAllActions: (count: number) => `نمایش همه ${count.toLocaleString('fa-IR')} مورد`,
      showFewerActions: 'نمایش کمتر',
      itemProgress: (position: number, total: number) =>
         `${position.toLocaleString('fa-IR')} از ${total.toLocaleString('fa-IR')}`,
      allClearTitle: 'صف توجه خالی است',
      allClearDescription: 'فعلا مانع، دیرکرد، فشار ظرفیت، هماهنگی یا ریسک پروژه‌ای که نیاز به تصمیم شما داشته باشد دیده نمی‌شود.',
      focusAttention: 'رسیدگی فوری',
      focusAttentionDescription: 'سیگنال‌هایی که همین امروز جلوی جریان کار را می‌گیرند.',
      focusDecisions: 'تصمیم‌های امروز',
      focusDecisionsDescription: 'بازبینی، تریاژ، واگذاری و مانع‌های منتظر تصمیم.',
      focusPeople: 'هماهنگی افراد',
      focusPeopleDescription: 'فشار کاری، چک‌این عقب‌افتاده و ۱:۱ نزدیک.',
      focusProjects: 'ریسک پروژه‌ها',
      focusProjectsDescription: 'پروژه‌هایی که سلامت یا آپدیت آن‌ها نیاز به پیگیری دارد.',
      openFocus: 'باز کردن',
      activeWork: 'کار فعال',
      attention: 'نیازمند توجه',
      workload: 'ظرفیت افراد',
      reviews: 'در انتظار بازبینی',
      blockers: 'مسدود و عقب‌افتاده',
      unassigned: 'بی‌مسئول و ورودی',
      projectHealth: 'سلامت پروژه‌ها',
      syncs: 'چک‌این و ۱:۱',
      overdue: 'عقب‌افتاده',
      blocked: 'مسدود',
      stale: 'راکد',
      backlog: 'بک‌لاگ',
      unassignedTasks: 'بی‌مسئول',
      overloaded: 'فشار بالا',
      idle: 'بدون کار فعال',
      noAttention: 'مورد فوری قابل مشاهده‌ای وجود ندارد.',
      noSyncs: 'چک‌این عقب‌افتاده یا ۱:۱ نزدیک وجود ندارد.',
      noQueueItems: 'موردی در این صف نیست.',
      openTask: 'باز کردن کار',
      openMembers: 'مشاهده اعضا',
      snooze: 'تعویق',
      snoozeDay: 'تعویق ۲۴ ساعته',
      resolve: 'حل شد',
      dismiss: 'رد کردن',
      dismissTitle: 'رد کردن مورد توجه',
      dismissDescription: 'علت رد شدن را کوتاه ثبت کنید تا بعدا مشخص باشد چرا این سیگنال از صف خارج شده است.',
      dismissReasonPlaceholder: 'مثلا: خارج از برنامه این هفته است یا از مسیر دیگری پیگیری می‌شود.',
      dismissConfirm: 'ثبت و رد کردن',
      actionFailed: 'عملیات روی مورد توجه ناموفق بود.',
      actionQueued: 'اقدام ذخیره شد و بعد از اتصال اعمال می‌شود.',
      queued: 'در صف',
      syncActionFailed: 'اقدام چک‌این یا ۱:۱ ناموفق بود.',
      generatedAt: 'آخرین محاسبه',
      truncated: 'داده‌ها محدود شده‌اند؛ برای تحلیل کامل فیلتر کنید.',
      noCheckInYet: 'هنوز چک‌این ثبت نشده است.',
      checkInAge: (hours: number) => `${hours.toLocaleString('fa-IR')} ساعت از آخرین چک‌این`,
      createOneOnOne: 'ساخت ۱:۱',
      openAgenda: 'دستور جلسه',
      noNextOneOnOne: 'زمان بعدی ثبت نشده است.',
      oneOnOneWith: (name: string) => `۱:۱ با ${name}`,
      agendaDescription: 'موضوع‌های پیشنهادی از توجه‌ها، موانع، چک‌این‌ها و اقدام‌های باز ساخته می‌شود و قبل از جلسه قابل ویرایش است.',
      openActionItems: 'کارهای خروجی باز',
      noOpenActionItems: 'کار خروجی بازی برای این ۱:۱ نیست.',
      completeActionItem: 'انجام شد',
      carryForwardActionItem: 'حمل به دستور جلسه',
      createLinkedTask: 'ساخت کار',
      actionItemCompleted: 'کار خروجی بسته شد.',
      actionItemCarried: 'کار خروجی به دستور جلسه اضافه شد.',
      actionItemTaskCreated: (key: string) => `کار ${key} از خروجی جلسه ساخته شد.`,
      generatedAgenda: 'پیشنهادهای دستور جلسه',
      noGeneratedAgenda: 'پیشنهاد تازه‌ای برای دستور جلسه نیست.',
      addToAgenda: 'افزودن',
      weightOfCapacity: (weight: number, capacity: number) =>
         `${weight.toLocaleString('fa-IR')} از ${capacity.toLocaleString('fa-IR')}`,
      taskCount: (count: number) => `${count.toLocaleString('fa-IR')} کار`,
      hourCount: (hours: number) => `${hours.toLocaleString('fa-IR')} ساعت`,
   },
   shortcuts: {
      title: 'میانبرهای صفحه‌کلید',
      description: 'میانبرهای سبک لینیر برای رابط راست‌به‌چپ تسکارا.',
      openCommandMenu: 'باز کردن منوی فرمان',
      createIssue: 'ایجاد کار',
      createIssueFullscreen: 'ایجاد کار در نمای تمام‌صفحه',
      toggleDetails: 'نمایش یا پنهان کردن جزئیات',
      moveRow: 'جابجایی بین ردیف‌ها',
      selectRow: 'انتخاب ردیف فعال',
      close: 'بستن یا پاک کردن انتخاب',
      openHelp: 'نمایش راهنمای میانبرها',
   },
   teamHealth: {
      loadFailed: 'بارگذاری سلامت تیم‌ها ناموفق بود.',
      generatedAt: 'آخرین محاسبه',
      diagnosticSurface: 'نمای تشخیصی تیم، بدون رتبه‌بندی افراد',
      truncated: 'فضای کاری بزرگ است؛ داده‌های صف‌ها محدود شده‌اند.',
      refresh: 'به‌روزرسانی',
      activeWork: 'کار فعال',
      overdue: 'عقب‌افتاده',
      blocked: 'مسدود',
      review: 'بازبینی',
      stale: 'راکد',
      active: 'فعال',
      overloaded: 'فشار بالا',
      unassigned: 'بی‌مسئول',
      projectRisk: 'ریسک پروژه',
      flowTitle: 'جریان و WIP',
      flowDescription: 'توزیع کار در وضعیت‌های اجرایی برای پیدا کردن تجمع و گلوگاه.',
      bottlenecksTitle: 'گلوگاه‌های قابل اقدام',
      bottlenecksDescription: 'صف‌هایی که اگر امروز رسیدگی شوند جریان کار تیم روان‌تر می‌شود.',
      peopleTitle: 'ظرفیت و بار افراد',
      peopleDescription: 'نمای ظرفیت، انسداد و بازبینی افراد برای بازتوزیع کار؛ این بخش رتبه‌بندی عملکرد نیست.',
      projectsTitle: 'ریسک پروژه‌ها',
      projectsDescription: 'پروژه‌هایی که به دلیل سلامت، انسداد، دیرکرد یا نبود آپدیت نیاز به تصمیم دارند.',
      emptyTitle: 'ریسک فعالی دیده نمی‌شود.',
      emptyDescription: 'وقتی کار، پروژه یا چک‌این وارد فضای کاری شود سلامت تیم‌ها اینجا به‌روزرسانی می‌شود.',
      noBottlenecks: 'گلوگاه فعالی نیست.',
      noBottlenecksDescription: 'صف‌های دیرکرد، انسداد، بازبینی و بی‌مسئول در محدوده قابل مشاهده خالی‌اند.',
      noPeopleRisk: 'فشار ظرفیت فعالی دیده نمی‌شود.',
      noPeopleRiskDescription: 'فردی با بار نامتوازن، انسداد یا بازبینی قابل توجه در محدوده قابل مشاهده نیست.',
      noProjectRisk: 'ریسک پروژه فعالی دیده نمی‌شود.',
      noProjectRiskDescription: 'پروژه‌های قابل مشاهده مسیر سالمی دارند یا هنوز کاری برای تحلیل ندارند.',
      overdueQueue: 'کارهای عقب‌افتاده',
      blockedQueue: 'کارهای مسدود',
      reviewQueue: 'صف بازبینی',
      staleQueue: 'کارهای راکد',
      unassignedQueue: 'کارهای بی‌مسئول',
      backlogQueue: 'ورودی بک‌لاگ',
      idle: 'بدون بار',
      balanced: 'متعادل',
      busy: 'پر',
      healthy: 'سالم',
      needsAttention: 'نیازمند توجه',
      atRisk: 'در ریسک',
      noLead: 'بدون لید',
      nextUpdate: 'آپدیت بعدی',
      lead: (name: string) => `لید: ${name}`,
      weightOfCapacity: (weight: number, capacity: number) =>
         `${weight.toLocaleString('fa-IR')} از ${capacity.toLocaleString('fa-IR')} وزن`,
   },
   table: {
      rank: 'رتبه',
      user: 'کاربر',
      role: 'نقش',
      phone: 'موبایل',
      mattermost: 'مترموست',
      joinedAt: 'عضویت از',
      changeRole: 'تغییر نقش',
      assigned: 'سپرده‌شده',
      done: 'انجام‌شده',
      speed: 'عملکرد',
      reported: 'گزارش‌شده',
      team: 'تیم',
      slug: 'شناسه',
      projects: 'پروژه‌ها',
      members: 'اعضا',
   },
} as const;
